### ISSUE TITLE
Pandas SettingWithCopyWarning error in some plots

### ISSUE THREAD

**Issue by StijnKas** [pegasystems/cdh-datascientist-tools#34]
As of right now, Pandas still gives some warnings because we change some values (for plotPredictorBinning) to percentages by setting to their name index (df['BinPropensity'] *= 100). This is not proper Pandas syntax and should be quite easily fixable.

**Comment by operdeck** [comment]
Maybe propensity does not even have to be multiplied? In ggplot I just
specify a scale in the plot itself, not in the data.

PS I now settled on Propensity, just calculating it slight differntly when
entrtype = Classifier.

Op wo 15 dec. 2021 15:30 schreef StijnKas ***@***.***>:

**Comment by StijnKas** [comment]
It seems Seaborn allows for this with an 'estimator' argument with a lambda function. Might be something to look into.
