### ISSUE TITLE
Not able to install CDH tools in R

### ISSUE THREAD

**Issue by abhitubu1** [pegasystems/cdh-datascientist-tools#44]
Hi Team,

I am getting an error while installing cdh tools package in R. The error comes in test_export_utils_JSON.R in the line where we are accessing singlebinpredictor.json file under test_that("ADM Factory to Binning more complex") . Can you please have a look.

Regards
Abhishek

**Comment by operdeck** [comment]
Hello Abhishek

Could you please include the exact command that you are executing and the
error messages?

Thanks


Op wo 26 jan. 2022 om 19:24 schreef abhitubu1 ***@***.***>:

**Comment by abhitubu1** [comment]
Hi Otto,

I am using install_github("pegasystems/cdh-datascientist-tools/r", build_vignettes=TRUE)

Regards
Abhishek

**Comment by StijnKas** [comment]
Hi Abhishek, could you please copy and paste the exact error message you're getting, along with some information about your system (OS, R version, etc)? Installing works fine for us, so we can't do much as of now. Thanks!

**Comment by operdeck** [comment]
Cannot reproduce
