### ISSUE TITLE
Unable to generate ModelReport and HealthCheck report

### ISSUE THREAD

**Issue by chandratmo** [pegasystems/cdh-datascientist-tools#45]
Hi Team, 

We have exported the model fact data and pred data as suggested ( download the file by exporting the data sets pyModelSnapShot and pyADMPredictorSnapShot in Pega) and trying to give the path to the locally saved files in the report modelreport.rmd and getting the below error. 
![image](https://user-images.githubusercontent.com/100797873/156428402-c00c29b7-72c2-446c-9dea-b9ffe4dea129.png)

and even after cleaning the pyName column , we are getting a new error that plot cannot be generated.

> # ggplotly(p) %>% layout(showlegend=FALSE) # plotly no use here given the way the plot is constructed
> p
Error: Faceting variables must have at least one value
Run `rlang::last_error()` to see where the error occurred.

Any pointers are what we are missing to generate a report based off our data.

Thanks in Advance.

Best,
Chandra

**Comment by operdeck** [comment]
Hello Chandra, thanks for filing the issue. First of all, the preferred way to export the file is using the dataset export from dev studio. This creates a (proprietary format) zip file that contains embedded JSONLD. This is described also in https://github.com/pegasystems/cdh-datascientist-tools/wiki/How-to-export-and-use-the-ADM-Datamart. It looks like you have exported a CSV file instead.

**Comment by operdeck** [comment]
Not closed - just wanted to comment

**Comment by chandratmo** [comment]
Hi Otto, 

Thanks for the suggestion.

The json file worked for me in generating the Health check report , however I am unbale to get the report in PDF or HTML or Word. When I use the option 'Knit to PDF' I am getting the below error.

processing file: healthcheck.Rmd
Quitting from lines 2-45 (healthcheck.Rmd) 
Error in eval(parse_only(code), envir = envir) : 
  object 'params' not found
Calls: <Anonymous> ... inline_exec -> hook_eval -> withVisible -> eval -> eval
Execution halted

No LaTeX installation detected (LaTeX is required to create PDF output). You should install a LaTeX distribution for your platform: https://www.latex-project.org/get/

  If you are not sure, you may install TinyTeX in R: tinytex::install_tinytex()

  Otherwise consider MiKTeX on Windows - http://miktex.org

  MacTeX on macOS - https://tug.org/mactex/
  (NOTE: Download with Safari rather than Chrome _strongly_ recommended)

  Linux: Use system package manager

**Comment by operdeck** [comment]
Hello Chandra,

If you say "the json file worked" I'm still wondering how you exported the data. As I mentioned before, the preferred option is to download the dataset from dev studio, which gives you a zip file that you should not unpack yourself. But anyway, glad you got it working.

For instructions on rendering a notebook to HTML (or other formats) I'm going to defer to info from e.g. https://bookdown.org/yihui/rmarkdown/documents.html (or dozens of other sites that describe this - just Google it). For context: rendering to HTML should not require any dependencies except perhaps pandoc. To render to PDF you need to install some version of LaTeX - as per the instructions you copied. However the PDF output of the health check doesn't have all the features (no interactive plots) so I would strongly recommend to stick to the HTML output.

Hope this helps and if you have other cdhtools specific questions, please file a new issue.

Regards

Otto

And PS: you can always share the data via my Pega account and I can quickly run the notebook for you
