### ISSUE TITLE
Unable to generate ModelReport and HealthCheck report

### ISSUE THREAD

**Issue by vanitmo** [pegasystems/cdh-datascientist-tools#50]
Hi Team,

We have exported the model fact data and pred data as suggested ( download the file by exporting the data sets pyModelSnapShot and pyADMPredictorSnapShot in Pega) and trying to give the path to the locally saved files in the report modelreport.rmd and getting the below errors.

Error in library(cdhtools) : there is no package called ‘cdhtools’

Error in hasMultipleSnapshots(datamart$modeldata) : 
  could not find function "hasMultipleSnapshots"

Thanks,
Vani

**Comment by operdeck** [comment]
Hi Vani,

This suggests you have not installed the package.

Please do follow the instructions on the Wiki (https://github.com/pegasystems/cdh-datascientist-tools/wiki) in the "Getting Started with the R Libary" section to install cdhtools. I'll update the instructions in the Wiki as I see they don't mention this currently.

Also, you mention you want to run the "health check" report. That is the healthcheck.Rmd file. In the text of the issue you refer to the other one. The modelreport.Rmd is used to create stand-alone model reports for ADM models (https://github.com/pegasystems/cdh-datascientist-tools/wiki/Create-stand-alone-Adaptive-Model-Reports).

Let us know if that solves the issue.

**Comment by operdeck** [comment]
Hi Vani,

Did your issue get resolved with the previous suggestions? 

Thx

Otto

**Comment by operdeck** [comment]
Hi Vani, 

I assume the issue got resolved. I'm closing it now. If you need assistance or run into problems please re-open or create another ticket. Thanks!
